// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.upuedu.hc.senior.model;

import com.upuedu.hc.senior.model.Task;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Task_Roo_Configurable {
    
    declare @type: Task: @Configurable;
    
}
